# Adds namespace to all resources.
namespace: default

# Labels to add to all resources and selectors.
commonLabels:
  app: testapp
  team: aura
# Each entry in this list must resolve to an existing
# resource definition in YAML.  These are the resource
# files that kustomize reads, modifies and emits as a
# YAML string, with resources separated by document
# markers ("---").
resources:
- nais.yaml
