[tool.poetry]
name = "doc"
version = "0.1.0"
description = "nais developer documentation"
authors = []

[tool.poetry.dependencies]
python = "^3.7"
mkdocs = "^1.1.2"
Pygments = "^2.7.2"
pymdown-extensions = "^8.0.1"
mkdocs-material = "^6.1.4"
mkdocs-build-plantuml-plugin = "^1.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
